FROM debian:12-slim AS build

ENV PREFIX=/root/opt/cross
ENV TARGET=i686-elf
ENV PATH="$PREFIX/bin:$PATH"

RUN mkdir -p /root/opt/cross

RUN apt update

RUN apt install --no-install-recommends -y \
                build-essential \
                bison \
                flex \
                libgmp3-dev \
                libmpc-dev \
                libmpfr-dev \
                texinfo \
                libisl-dev

RUN apt install --no-install-recommends -y \
                wget \
                grub-common \
                xorriso

RUN mkdir /root/src
RUN cd /root/src

RUN wget https://ftp.gnu.org/gnu/binutils/binutils-2.44.tar.gz
RUN wget https://ftp.gnu.org/gnu/gcc/gcc-14.2.0/gcc-14.2.0.tar.gz

RUN tar xzf binutils-2.44.tar.gz
RUN tar xzf gcc-14.2.0.tar.gz

RUN mkdir /root/src/build-binutils
RUN cd /root/src/build-binutils
RUN ../binutils-2.44/configure --target=$TARGET --prefix=$PREFIX --with-sysroot --disable-nls --disable-werror
RUN make -j8
RUN make install

RUN mkdir /root/src/build-gcc
RUN cd /root/src/build-gcc
RUN ../gcc-14.2.0/configure --target=$TARGET --prefix=$PREFIX --disable-nls --enable-languages=c,c++ --without-headers --disable-hosted-libstdcxx
RUN make all-gcc -j8
RUN make all-target-libgcc -j8
RUN make all-target-libstdc++-v3 -j8
RUN make install-gcc
RUN make install-target-libgcc
RUN make install-target-libstdc++-v3


FROM debian:12-slim

ENV PREFIX=/root/opt/cross
ENV TARGET=i686-elf
ENV PATH="$PREFIX/bin:$PATH"

RUN mkdir -p /root/opt/cross

COPY --from=build /root/opt/cross/* /root/opt/cross/*

RUN apt update

RUN apt install --no-install-recommends -y \
                build-essential \
                bison \
                flex \
                libgmp3-dev \
                libmpc-dev \
                libmpfr-dev \
                texinfo \
                libisl-dev

RUN apt install --no-install-recommends -y \
                wget \
                grub-common \
                xorriso

CMD ["i686-elf-gcc"]